### ISSUE TITLE
Module name containing _ aren't accepted

### ISSUE THREAD

**Issue by jfmengels** [elm/project-metadata-utils#12]
## Summary

When the module name contains `_`, `Elm.Module.fromString` will return `Nothing`, and `Elm.Module.decoder` will fail. Since these are used in `Elm.Project.decoder`, this means that 

There are modules out there, that contain modules containing an `_`. I encountered this in https://package.elm-lang.org/packages/AdrianRibao/elm-derberos-date/1.2.3/, but there may be others.

## SSCCE

You can use this `elm.json` file:
https://package.elm-lang.org/packages/AdrianRibao/elm-derberos-date/1.2.3/elm.json

Here is an Ellie where we attempt to decode it: https://ellie-app.com/8W4c6qXQFgwa1

## Additional details

Context: I use `elm/project-metadata-utils` in `elm-review` to decode `elm.json` files in order to use the information about a dependency, and use it to provide helpful analysis. Unfortunately, this dependency is not decodable using the current implementation.

@rlefevre pointed me towards the [compiler's code that validates module names](https://github.com/elm/compiler/blob/c4a81fcde7efe9199c0037d1810c08b32ebb7d08/compiler/src/Parse/Variable.hs#L326). From our understanding, unicode is accepted in module names, but they wouldn't be accepted with this decoder's implementation. So both `_` and unicode support are missing at the moment.

**Comment by rupertlssmith** [comment]
Which solution would be better to make this and the compiler match - to add unicode support here? OR to remove unicode support from the compiler?

**Comment by jfmengels** [comment]
Add support for unicode here would be better.
Removing it from the language would be a breaking change that isn't warranted by this situation.

**Comment by rupertlssmith** [comment]
The above patch is only a fix for _, it does not do anything about unicode.

**Comment by jfmengels** [comment]
In `stil4m/elm-syntax` we recently started using [`miniBill/elm-unicode`](https://package.elm-lang.org/packages/miniBill/elm-unicode/latest/) to parse function/type names with unicode characters and it's working well so far.

**Comment by evancz** [comment]
Fixed by #13. Let's do a new issue for unicode. I'd want any logic for that to be contained within this package though. That way `elm` packages only rely on other `elm` packages.
