### ISSUE TITLE
Module name containing numbers are not considered valid.

### ISSUE THREAD

**Issue by norpan** [elm/project-metadata-utils#3]
I got the following error message:
```
Problem with the value at json[0]: "Html5.DragDrop" I need a valid module name like "Json.Decode"
```
but as far as I know, it's ok to have numbers in your module names.

**Comment by evancz** [comment]
I need an https://sscce.org/ to work on these sorts of things. Please open a new issue with steps to reproduce. Read what an SSCCE is though. I need that on all issues.
